# -*- coding: utf-8 -*-
"""2Layer_CV_RNN_LSTM.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1jrKP4mQMZLp9oU-zZSQpx4g7FPaOTA-H
"""

import os
import tensorflow.keras as keras
import tensorflow as tf
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
import pandas as pd
from keras.models import Sequential
from keras.layers import LSTM, Dropout, Dense
from sklearn.model_selection import train_test_split
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from tensorflow.keras.optimizers import Adam, SGD, Adagrad, RMSprop
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, TensorBoard
import pickle as p
import glob
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Input, Masking

from google.colab import drive
drive.mount('/content/drive')

file_path = "/content/drive/MyDrive/assignment2/CV_Data01"
classes = ['ba', 'hai','hI', 'ka','ni']
data_split = ['Test', 'Train']

Y_train = []
X_train = []
X_test = []
Y_test = []

dir_list = os.listdir(file_path)
print(dir_list)
for j in data_split:
    for i in classes:
        for filename in glob.glob(os.path.join(file_path + '/' + i + '/' + j, '*.mfcc')):
            with open(filename, 'r') as f:
                if (j == "Train"):
                    # print(filename)
                    f = open(filename)
                    parsed = f.readlines()
                    parsed = [np.array([float(val) for val in line.split(" ") if val!="\n"]) for line in parsed]
                    X_train.append(np.array(parsed))
                    Y_train.append(str(i))
                if (j == 'Test'):
                    # print(filename)
                    f = open(filename)
                    parsed = f.readlines()
                    parsed = [np.array([float(val) for val in line.split(" ") if val!="\n"]) for line in parsed]
                    X_test.append(np.array(parsed))
                    Y_test.append(str(i))
print("Training Set has {} samples each with dimension {} but variable length".format(len(X_train),X_train[0][0].shape))
print("Test Set has {} samples each with dimension {} but variable length".format(len(X_test),X_test[0][0].shape))


# padding input
max_len = max([len(val) for val in X_train])
print("Max_seq length: ",max_len)
def padd_it(data):
    for i in range(len(data)):
        if len(data[i]) <= max_len:
            seq = np.repeat(np.array([-1]*39).reshape(-1,39),int(max_len-len(data[i])),0)
            data[i] = np.append(data[i],seq,axis=0)
    return data
# data preprocessing steps to prepare the input data for training and testing a model
print("Before Padding shape of first element in train is {}".format((X_train[0]).shape))
X_test = np.asarray(padd_it(X_test))
X_train = np.asarray(padd_it(X_train))
print("After Padding shape of first element in train is {}".format((X_train[0]).shape))

type(X_train)

X_train.shape

Y_train=np.array(Y_train).reshape(-1, 1)

Y_test=np.array(Y_test).reshape(-1, 1)

from numpy import asarray
from sklearn.preprocessing import OrdinalEncoder
#define ordinal encoding
encoder = OrdinalEncoder()
# transform data
yt= encoder.fit_transform(Y_train)
print(yt)

ytest= encoder.fit_transform(Y_test)
print(ytest)

CV_RNN_Model1=Sequential()
CV_RNN_Model1.add(Masking(mask_value=-1,input_shape=X_train.shape[1:]))  # to mask values other then -1 (padded value that shall be ignored)
CV_RNN_Model1.add(SimpleRNN(32, return_sequences=False))
CV_RNN_Model1.add(Dropout(0.2))
CV_RNN_Model1.add(Dense(5, activation='softmax'))
CV_RNN_Model1.summary()

CV_RNN_Model1.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=['accuracy'])
callback = tf.keras.callbacks.EarlyStopping(monitor="loss", min_delta=0.0001,patience=3)
history = CV_RNN_Model1.fit(X_train, yt, batch_size=32,callbacks=[callback] ,epochs=500,verbose=1)

CV_RNN_Model1.save('/content/drive/MyDrive/CV_RNN_Model1.h5')

#Save Model and Model Structure
CV_RNN_Model1.save('/content/drive/MyDrive/DLA6/CV_SAVE_Model/RNN_CV1L32.h5')
f=open('/content/drive/MyDrive/DLA6/CV_SAVE_Model/RNN_CV_HIST1L32.pckl','wb')
p.dump(history.history,f)
f.close()

# Extract the loss values from the history object
training_loss = history.history['loss']

#Plot the training loss against epochs
epochs = range(1, len(training_loss) + 1)
plt.plot(epochs, training_loss, 'b', label='Average Training Error')
plt.xlabel('Epochs')
plt.ylabel('Average Training Error')
plt.title('Average Training Error vs. Epochs')
plt.legend()
plt.show()



CV_RNN_Model1.evaluate(X_train,yt)
CV_RNN_Model1.evaluate(X_test,ytest)

#Evaluating the model
print('\nEvaluation of model on train data:')
trainAcc1=CV_RNN_Model1.evaluate(x=X_train,y=yt,batch_size=1, verbose="auto",callbacks=None)
print(CV_RNN_Model1.metrics_names)
print(trainAcc1)
print('\nEvaluation of model on test data:')
testAcc1=CV_RNN_Model1.evaluate(x=X_test, y=ytest, batch_size=1, verbose="auto",callbacks=None)
print(CV_RNN_Model1.metrics_names)
print(testAcc1)
print('\nPredictions for test data:')
testProb1=CV_RNN_Model1.predict(X_test, batch_size=1, verbose="auto", callbacks=None)
pred1=np.argmax(testProb1,axis=1)
confusionMatrix1=tf.math.confusion_matrix(ytest,pred1)
print(confusionMatrix1)

plt.figure(figsize=(8, 6))
#plt.plot(history8.history['accuracy'])
plt.plot(history.history['loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
#plt.legend(['train', 'test'], loc='upper left')
plt.show()

from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint, TensorBoard

es1= EarlyStopping(monitor='loss',min_delta=0.0001, patience=20,verbose=1)

mask_value=0.0
model1 = Sequential()
model1.add(Masking(mask_value = -1 , input_shape = X_train.shape[1:]))
model1.add(SimpleRNN(units=64,return_sequences=True))
model1.add(Dropout(0.2))
#model.add(SimpleRNN(units=64,return_sequences=True))
#model.add(Dropout(0.2))
model1.add(SimpleRNN(units=64))
model1.add(Dense(units=5, activation='softmax'))
model1.compile(loss = 'sparse_categorical_crossentropy', optimizer='adam', metrics = ['accuracy'])
#model1.summary()
history1=model1.fit(X_train, yt, callbacks=[es1],epochs=1000, batch_size=128)

model1.save('/content/drive/MyDrive/modela.h5')

#Evaluating the model
print('\nEvaluation of model on train data:')
trainAcc1=model1.evaluate(x=X_train,y=yt,batch_size=1, verbose="auto",callbacks=None)
print(model1.metrics_names)
print(trainAcc1)
print('\nEvaluation of model on test data:')
testAcc1=model1.evaluate(x=X_test, y=ytest, batch_size=1, verbose="auto",callbacks=None)
print(model1.metrics_names)
print(testAcc1)
print('\nPredictions for test data:')
testProb1=model1.predict(X_test, batch_size=1, verbose="auto", callbacks=None)
pred1=np.argmax(testProb1,axis=1)
confusionMatrix1=tf.math.confusion_matrix(ytest,pred1)
print(confusionMatrix1)

plt.figure(figsize=(8, 6))
#plt.plot(history8.history['accuracy'])
plt.plot(history1.history['loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
#plt.legend(['train', 'test'], loc='upper left')
plt.show()

es2= EarlyStopping(monitor='loss',min_delta=0.0001, patience=20,verbose=1)

mask_value=0.0
model2 = Sequential()
model2.add(Masking(mask_value = -1 , input_shape = X_train.shape[1:]))
model2.add(SimpleRNN(units=32,return_sequences=True))
model2.add(Dropout(0.2))
#model.add(SimpleRNN(units=64,return_sequences=True))
#model.add(Dropout(0.2))
model2.add(SimpleRNN(units=32))
model2.add(Dense(units=5, activation='softmax'))
model2.compile(loss = 'sparse_categorical_crossentropy', optimizer='adam', metrics = ['accuracy'])
model2.summary()
history2=model2.fit(X_train, yt, callbacks=[es2],epochs=1000, batch_size=128)

model2.save('/content/drive/MyDrive/model2a.h5')

#Evaluating the model
print('\nEvaluation of model on train data:')
trainAcc2=model2.evaluate(x=X_train,y=yt,batch_size=1, verbose="auto",callbacks=None)
print(model2.metrics_names)
print(trainAcc2)
print('\nEvaluation of model on test data:')
testAcc2=model2.evaluate(x=X_test, y=ytest, batch_size=1, verbose="auto",callbacks=None)
print(model2.metrics_names)
print(testAcc2)
print('\nPredictions for test data:')
testProb2=model2.predict(X_test, batch_size=1, verbose="auto", callbacks=None)
pred2=np.argmax(testProb2,axis=1)
confusionMatrix2=tf.math.confusion_matrix(ytest,pred2)
print(confusionMatrix2)

plt.figure(figsize=(8, 6))
#plt.plot(history8.history['accuracy'])
plt.plot(history2.history['loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
#plt.legend(['train', 'test'], loc='upper left')
plt.show()

es3= EarlyStopping(monitor='loss',min_delta=0.0001, patience=20,verbose=1)

mask_value=0.0
model3 = Sequential()
model3.add(Masking(mask_value = -1 , input_shape = X_train.shape[1:]))
model3.add(SimpleRNN(units=128,return_sequences=True))
model3.add(Dropout(0.2))
#model.add(SimpleRNN(units=64,return_sequences=True))
#model.add(Dropout(0.2))
model3.add(SimpleRNN(units=128))
model3.add(Dense(units=5, activation='softmax'))
model3.compile(loss = 'sparse_categorical_crossentropy', optimizer='adam', metrics = ['accuracy'])
model3.summary()
history3=model3.fit(X_train, yt, callbacks=[es3],epochs=1000, batch_size=128)

model3.save('/content/drive/MyDrive/model3a.h5')

#Evaluating the model
print('\nEvaluation of model on train data:')
trainAcc3=model3.evaluate(x=X_train,y=yt,batch_size=1, verbose="auto",callbacks=None)
print(model3.metrics_names)
print(trainAcc3)
print('\nEvaluation of model on test data:')
testAcc3=model3.evaluate(x=X_test, y=ytest, batch_size=1, verbose="auto",callbacks=None)
print(model3.metrics_names)
print(testAcc3)
print('\nPredictions for test data:')
testProb3=model3.predict(X_test, batch_size=1, verbose="auto", callbacks=None)
pred3=np.argmax(testProb3,axis=1)
confusionMatrix3=tf.math.confusion_matrix(ytest,pred3)
print(confusionMatrix3)

plt.figure(figsize=(8, 6))
#plt.plot(history8.history['accuracy'])
plt.plot(history3.history['loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
#plt.legend(['train', 'test'], loc='upper left')
plt.show()

es6= EarlyStopping(monitor='loss',min_delta=0.0001, patience=20,verbose=1)

mask_value=0.0
model6 = Sequential()
model6.add(Masking(mask_value = -1 , input_shape = X_train.shape[1:]))
model6.add(LSTM(units=32,return_sequences=True))
model6.add(Dropout(0.2))
#model.add(LSTM(units=32,return_sequences=True))
#model.add(Dropout(0.2))
model6.add(LSTM(units=32))
#model.add(Dropout(0.2))
model6.add(Dense(units=5, activation='softmax'))
model6.compile(loss = 'sparse_categorical_crossentropy', optimizer='adam', metrics = ['accuracy'])
model6.summary()
history6=model6.fit(X_train, yt, callbacks=[es6],epochs=1000, batch_size=128)

model6.save('/content/drive/MyDrive/model6a.h5')

#Evaluating the model
print('\nEvaluation of model on train data:')
trainAcc6=model6.evaluate(x=X_train,y=yt,batch_size=1, verbose="auto",callbacks=None)
print(model6.metrics_names)
print(trainAcc6)
print('\nEvaluation of model on test data:')
testAcc6=model6.evaluate(x=X_test, y=ytest, batch_size=1, verbose="auto",callbacks=None)
print(model6.metrics_names)
print(testAcc6)
print('\nPredictions for test data:')
testProb6=model6.predict(X_test, batch_size=1, verbose="auto", callbacks=None)
pred6=np.argmax(testProb6,axis=1)
confusionMatrix6=tf.math.confusion_matrix(ytest,pred6)
print(confusionMatrix6)

plt.figure(figsize=(8, 6))
#plt.plot(history8.history['accuracy'])
plt.plot(history6.history['loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
#plt.legend(['train', 'test'], loc='upper left')
plt.show()

es7= EarlyStopping(monitor='loss',min_delta=0.0001, patience=20,verbose=1)

mask_value=0.0
model7 = Sequential()
model7.add(Masking(mask_value = -1 , input_shape = X_train.shape[1:]))
model7.add(LSTM(units=64,return_sequences=True))
model7.add(Dropout(0.2))
#model.add(LSTM(units=32,return_sequences=True))
#model.add(Dropout(0.2))
model7.add(LSTM(units=64))
#model.add(Dropout(0.2))
model7.add(Dense(units=5, activation='softmax'))
model7.compile(loss = 'sparse_categorical_crossentropy', optimizer='adam', metrics = ['accuracy'])
model7.summary()
history7=model7.fit(X_train, yt, callbacks=[es6],epochs=1000, batch_size=128)

model7.save('/content/drive/MyDrive/model7a.h5')

print('\nEvaluation of model on train data:')
trainAcc7=model7.evaluate(x=X_train,y=yt,batch_size=1, verbose="auto",callbacks=None)
print(model7.metrics_names)
print(trainAcc7)
print('\nEvaluation of model on test data:')
testAcc7=model7.evaluate(x=X_test, y=ytest, batch_size=1, verbose="auto",callbacks=None)
print(model7.metrics_names)
print(testAcc7)
print('\nPredictions for test data:')
testProb7=model7.predict(X_test, batch_size=1, verbose="auto", callbacks=None)
pred7=np.argmax(testProb7,axis=1)
confusionMatrix7=tf.math.confusion_matrix(ytest,pred7)
print(confusionMatrix7)

plt.figure(figsize=(8, 6))
#plt.plot(history8.history['accuracy'])
plt.plot(history7.history['loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
#plt.legend(['train', 'test'], loc='upper left')
plt.show()

es8= EarlyStopping(monitor='loss',min_delta=0.0001, patience=20,verbose=1)

mask_value=0.0
model8 = Sequential()
model6.add(Masking(mask_value = -1 , input_shape = X_train.shape[1:]))
model8.add(LSTM(units=128,return_sequences=True))
model8.add(Dropout(0.2))
#model.add(LSTM(units=32,return_sequences=True))
#model.add(Dropout(0.2))
model8.add(LSTM(units=128))
#model.add(Dropout(0.2))
model8.add(Dense(units=5, activation='softmax'))
model8.compile(loss = 'sparse_categorical_crossentropy', optimizer='adam', metrics = ['accuracy'])
#model8.summary()
history8=model8.fit(X_train, yt, callbacks=[es8],epochs=1000, batch_size=128)

model8.save('/content/drive/MyDrive/model8a.h5')

#Evaluating the model
print('\nEvaluation of model on train data:')
trainAcc8=model8.evaluate(x=X_train,y=yt,batch_size=1, verbose="auto",callbacks=None)
print(model8.metrics_names)
print(trainAcc8)
print('\nEvaluation of model on test data:')
testAcc8=model8.evaluate(x=X_test, y=ytest, batch_size=1, verbose="auto",callbacks=None)
print(model8.metrics_names)
print(testAcc8)
print('\nPredictions for test data:')
testProb8=model8.predict(X_test, batch_size=1, verbose="auto", callbacks=None)
pred8=np.argmax(testProb8,axis=1)
confusionMatrix8=tf.math.confusion_matrix(ytest,pred8)
print(confusionMatrix8)

plt.figure(figsize=(8, 6))
#plt.plot(history8.history['accuracy'])
plt.plot(history8.history['loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
#plt.legend(['train', 'test'], loc='upper left')
plt.show()

